# Generated by Django 4.0.6 on 2022-08-04 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='введите ФИО', max_length=100, verbose_name='ФИО')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(help_text='формат: 00.00.0000', verbose_name='Дата рождения')),
                ('class_student', models.CharField(help_text='формат: 1-класс, группа-a, b, c', max_length=100, verbose_name='Класс')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=100, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото(необязательно)')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_school', models.CharField(help_text='формат: 1-класс, группа-a, b, c', max_length=100, verbose_name='Класс')),
                ('item_name', models.CharField(choices=[('Математика', 'Математика'), ('Труд', 'Труд'), ('Музыка', 'Музыка'), ('Русский язык', 'Русский язык'), ('Физкультура', 'Физкультура'), ('Родной язык', 'Родной язык'), ('История', 'История'), ('Литература', 'Литература'), ('Технология', 'Технология'), ('География', 'География'), ('Биология', 'Биология'), ('Информатика', 'Информатика'), ('Черчение', 'Черчение'), ('Алгебра', 'Алгебра'), ('Геометрия', 'Геометрия'), ('Физика', 'Физика'), ('Химия', 'Химия'), ('Философия', 'Философия')], max_length=100, verbose_name='Название предмета')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'учитель',
                'verbose_name_plural': 'учителя',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название школы')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('slug', models.SlugField(blank=True)),
                ('class_students', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='school_class', to='school.classchoice', verbose_name='класс')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.AddField(
            model_name='classchoice',
            name='student',
            field=models.ManyToManyField(to='school.student', verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='classchoice',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='school.teacher', verbose_name='Учитель'),
        ),
    ]
