# Generated by Django 4.0.6 on 2022-07-30 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(help_text='например: A, B, Г, Д', max_length=100, verbose_name='Название класса')),
                ('class_number', models.CharField(choices=[('1', '1-класс'), ('2', '2-класс'), ('3', '3-класс'), ('4', '4-класс'), ('5', '5-класс'), ('6', '6-класс'), ('7', '7-класс'), ('8', '8-класс'), ('9', '9-класс'), ('10', '10-класс'), ('11', '11-класс')], max_length=100, verbose_name='Выбор класса')),
            ],
            options={
                'verbose_name': 'Название класса',
                'verbose_name_plural': 'Название классов',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('item_name', models.CharField(choices=[('1', 'Математика'), ('2', 'Труд'), ('3', 'Музыка'), ('4', 'Русский язык'), ('5', 'Физкультура '), ('6', 'Родной язык'), ('7', 'История'), ('8', 'Литература'), ('9', 'Технология'), ('10', 'География'), ('11', 'Биология'), ('12', 'Информатика'), ('13', 'Черчение'), ('14', 'Алгебра'), ('15', 'Геометрия'), ('16', 'Физика'), ('17', 'Химия'), ('18', 'Философия')], max_length=100, verbose_name='Название предмета')),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='school.classstudent', verbose_name='Класс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'учитель',
                'verbose_name_plural': 'учителя',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='введите ФИО', max_length=100, verbose_name='ФИО')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_of_birth', models.DateField(help_text='формат: 00.00.0000', verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('sex', models.CharField(choices=[('1', 'мужской'), ('2', 'женский')], max_length=100, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото(необязательно)')),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='school.classstudent', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название школы')),
                ('class_students', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='school_class', to='school.classchoice', verbose_name='класс')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.AddField(
            model_name='classchoice',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.classstudent'),
        ),
        migrations.AddField(
            model_name='classchoice',
            name='student',
            field=models.ManyToManyField(to='school.student', verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='classchoice',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='school.teacher'),
        ),
    ]
