# Generated by Django 4.0.6 on 2022-07-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classchoice_user_classstudent_user_school_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classchoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
