# Generated by Django 4.0.6 on 2022-07-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_slug_alter_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
