# Generated by Django 4.0.6 on 2022-07-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
