# Generated by Django 4.0.6 on 2022-07-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=100, verbose_name='Пол'),
        ),
    ]
