# Generated by Django 4.0.6 on 2022-07-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_student_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_student',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_school',
            field=models.CharField(default=1, help_text='формат: 1-класс, группа-a, b, c', max_length=100, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classchoice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='classchoice',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='school.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_student',
            field=models.CharField(max_length=100, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='item_name',
            field=models.CharField(choices=[('Математика', 'Математика'), ('Труд', 'Труд'), ('Музыка', 'Музыка'), ('Русский язык', 'Русский язык'), ('Физкультура', 'Физкультура'), ('Родной язык', 'Родной язык'), ('История', 'История'), ('Литература', 'Литература'), ('Технология', 'Технология'), ('География', 'География'), ('Биология', 'Биология'), ('Информатика', 'Информатика'), ('Черчение', 'Черчение'), ('Алгебра', 'Алгебра'), ('Геометрия', 'Геометрия'), ('Физика', 'Физика'), ('Химия', 'Химия'), ('Философия', 'Философия')], max_length=100, verbose_name='Название предмета'),
        ),
        migrations.DeleteModel(
            name='ClassStudent',
        ),
    ]
