# Generated by Django 4.0.6 on 2022-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_student_class_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
