# Generated by Django 4.0.6 on 2022-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_school_name_alter_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
